### ISSUE TITLE
Inquiry about the inaccurate 3d human pose labels

### ISSUE THREAD

**Issue by keqizero** [egeozsoy/4D-OR#4]
Hi, thank you for your great work, but I am facing a problem about the accuracy of the 3d human pose labels. 

I was running the 3d human pose estimation experiment based on VoxelPose, but according to the visualization of the projected 2d views ('image_with_joints' folder), the gt labels are often inaccurate. I am attaching some of the visualization results. 

I checked the code, but I don't see any problems. So I want to ask that does this kind of inaccuracy meet the expectations? Because I don't know the details of the annotation process.

Thank you! 

![train_00000000_view_1_gt](https://github.com/egeozsoy/4D-OR/assets/27662567/415d6b92-ee70-471d-81a9-9a9c88a24d42)
![validation_00000433_view_2_gt](https://github.com/egeozsoy/4D-OR/assets/27662567/5e909e47-7ca0-40ff-b63f-9b2b42780113)

**Comment by egeozsoy** [comment]
Hi, thank you for your interest. The human poses are semi automatically annotated and might not always be perfect. In the bottom examples you sent I think the issue is the human is actually not visible in the point cloud, and the human pose track stays at the last spot where the human was detected. This might be an error in the code but also potentially an error in the annotations. 

However in the other examples I think it is not as bad. You can try to visualize the pose from only one human to see the accuracy. I think overlaying all points from all humans makes it hard to judge. 

Finally if you are looking for better human pose annotations, you should check out https://github.com/CAMMA-public/MVOR. The annotations are more precise, however the dataset is much smaller. So you can see which fits your needs the best, maybe both together?

hope these help

**Comment by keqizero** [comment]
> Hi, thank you for your interest. The human poses are semi automatically annotated and might not always be perfect. In the bottom examples you sent I think the issue is the human is actually not visible in the point cloud, and the human pose track stays at the last spot where the human was detected. This might be an error in the code but also potentially an error in the annotations.
> 
> However in the other examples I think it is not as bad. You can try to visualize the pose from only one human to see the accuracy. I think overlaying all points from all humans makes it hard to judge.
> 
> Finally if you are looking for better human pose annotations, you should check out https://github.com/CAMMA-public/MVOR. The annotations are more precise, however the dataset is much smaller. So you can see which fits your needs the best, maybe both together?
> 
> hope these help

Okay I get it. Thank you for your kind reply!
